# Generated by Django 4.0.1 on 2022-01-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foha_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomes', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_funcionario', models.IntegerField()),
                ('id_provento', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
