# Generated by Django 4.0.1 on 2022-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_depto', models.IntegerField()),
                ('id_municipio', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
    ]
