# Generated by Django 4.0.1 on 2022-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_setor', models.IntegerField()),
                ('id_depto', models.IntegerField()),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
    ]
