# Generated by Django 4.0.1 on 2022-02-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_setor_id_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='modelo',
            field=models.IntegerField(default=0),
        ),
    ]
