# Generated by Django 4.0.1 on 2022-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_municipio_string_pesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcionario', models.IntegerField()),
                ('id_depto', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_municipio', models.IntegerField()),
                ('id_funcao', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.IntegerField(default=1)),
            ],
        ),
    ]
