# Generated by Django 4.0.1 on 2022-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_cargo_vinculo_funcionario_id_cargo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'cargo'), name='unique cargo'),
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='Cargo',
        ),
    ]
