# Generated by Django 4.0.1 on 2022-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_cargo_unique cargo_alter_cargo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id_repartition', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('id_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'Repartition',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.IntegerField(primary_key=True, serialize=False)),
                ('id_repartition', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('id_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'vinculo'), name='unique vinculo'),
        ),
        migrations.AlterModelTable(
            name='vinculo',
            table='Vinculo',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('nome', 'id_municipio'), name='section nome'),
        ),
        migrations.AddConstraint(
            model_name='repartition',
            constraint=models.UniqueConstraint(fields=('nome', 'id_municipio'), name='repartition nome'),
        ),
    ]
