# Generated by Django 4.0.1 on 2022-02-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_repartition_section_vinculo_unique vinculo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repartition',
        ),
    ]
