# Generated by Django 4.0.1 on 2022-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_delete_repartition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id_repartition', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('id_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'Repartition',
            },
        ),
        migrations.AddConstraint(
            model_name='repartition',
            constraint=models.UniqueConstraint(fields=('nome', 'id_municipio'), name='repartition nome'),
        ),
    ]
