# Generated by Django 4.0.1 on 2022-02-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_repartition_repartition_repartition nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
