# Generated by Django 4.0.1 on 2022-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('id_repartition', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(default='', max_length=50)),
                ('id_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('nome', 'id_municipio'), name='section nome'),
        ),
    ]
