# Generated by Django 4.0.1 on 2022-02-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_section_section_section nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
