# Generated by Django 4.0.1 on 2022-02-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_cargo_cargo_unique cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
