# Generated by Django 4.0.1 on 2022-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_delete_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
                ('modelo', models.IntegerField(default=0)),
                ('string_pesquisa', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
    ]
