# Generated by Django 4.0.1 on 2022-02-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_municipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
