# Generated by Django 4.0.1 on 2022-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_delete_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('codigo', models.CharField(default='', max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
    ]
