# Generated by Django 4.0.1 on 2022-02-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_setor_setor_unique setor setor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
