# Generated by Django 4.0.1 on 2022-02-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_cargo_cargo_unique cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
