# Generated by Django 4.0.1 on 2022-02-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_delete_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('cargo', models.CharField(max_length=100)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'cargo'), name='unique cargo'),
        ),
    ]
