# Generated by Django 4.0.1 on 2022-02-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_vinculo_vinculo_unique vinculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
