# Generated by Django 4.0.1 on 2022-02-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_departamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
