# Generated by Django 4.0.1 on 2022-02-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_delete_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('id_departamento', models.IntegerField()),
                ('id_municipio', models.IntegerField(default=0)),
                ('setor', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Setor',
            },
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'setor'), name='unique setor setor'),
        ),
    ]
