# Generated by Django 4.0.1 on 2022-02-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_setor_setor_unique setor setor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
