# Generated by Django 4.0.1 on 2022-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_setor_setor_unique setor setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folha',
            fields=[
                ('id_folha', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('anomes', models.IntegerField()),
                ('codigo_funcionario', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('id_departamento', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_cargo', models.IntegerField()),
                ('id_vinculo', models.IntegerField()),
                ('id_provento', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'folha',
            },
        ),
        migrations.DeleteModel(
            name='Foha_01',
        ),
    ]
