# Generated by Django 4.0.1 on 2022-02-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0042_folha_delete_foha_01'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repartition',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RemoveField(
            model_name='folha',
            name='nome',
        ),
    ]
