# Generated by Django 4.0.1 on 2022-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0043_delete_repartition_delete_section_remove_folha_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvDesc',
            fields=[
                ('id_provdesc', models.AutoField(primary_key=True, serialize=False)),
                ('id_municipio', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('codigo', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provdesc',
            },
        ),
        migrations.AddConstraint(
            model_name='provdesc',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'codigo'), name='provdesc unique codigo'),
        ),
    ]
