# Generated by Django 4.0.1 on 2022-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0044_provdesc_provdesc_provdesc unique codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='folha',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
