# Generated by Django 4.0.1 on 2022-02-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0045_folha_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
