# Generated by Django 4.0.1 on 2022-02-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0046_delete_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcionario', models.IntegerField()),
                ('id_departamento', models.IntegerField()),
                ('id_setor', models.IntegerField()),
                ('id_cargo', models.IntegerField(default=0)),
                ('id_vinculo', models.IntegerField(default=0)),
                ('id_municipio', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('data_admissao', models.DateField(null=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(fields=('id_municipio', 'codigo'), name='funcionario unique codigo'),
        ),
    ]
