# Generated by Django 4.0.1 on 2022-02-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0049_funcionario_funcionario_funcionario unique codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folha',
        ),
    ]
