# Generated by Django 4.0.1 on 2022-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0051_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='provdesc',
            name='ordenacao1',
            field=models.IntegerField(default=0),
        ),
    ]
