# Generated by Django 4.0.1 on 2022-02-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0052_provdesc_ordenacao1'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='carga_horaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='jornada',
            field=models.IntegerField(default=0),
        ),
    ]
